# 
#  Rakefile
#  falling_stuff
#  
#  Created by Paulo Schneider on 2008-03-05.
#  Copyright 2008 Jeek Labs. All rights reserved.
# 

require 'rawr'

NAME="Falling Stuff"
JAR_NAME="fs.jar"
BUILD_DIR="build"

namespace :jl do
  desc"Start game"
  task :play do
    sh "export CLASSPATH=java_lib/slick.jar:java_lib/lwjgl.jar; jruby -J-Djava.library.path=java_lib/native_files bin/main.rb"
  end

  desc "Creates a Mac OS X binary"
  task :mac_binary => [:jar_distribution] do
  end

  desc "Creates a Web Start application"
  task :webstart => [:jar_distribution] do
    sh "jarsigner -keystore jl_keystore build/fs.jar myself"
  end

  desc "Creates the JAR distribution file"
  task :jar_distribution do
    jar_dest = "#{BUILD_DIR}/#{JAR_NAME}"
    FileUtils.rm(jar_dest) if File.exists? jar_dest

    FileUtils.copy("java_lib/jruby.jar", "jruby.jar")
    sh "jar uvf jruby.jar bin/ lib/ resources/ java_lib/"
    FileUtils.move("jruby.jar", jar_dest)
  end
end
